### ISSUE TITLE
Library Browser is dropping top folder if it is one letter long

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#725] opened 2022-09-12 17:52 UTC
In a new 2.17 server, in a test course, I made a folder "a" in the templates folder.

(Actually I symlinked to "t" in /opt/webwork/pg" but have since found a simpler MWE.)

Inside a/, put a pg file. It could just be an empty "file.pg" if you want as long as it has the .pg extension.

Now go to Library Browser and click Local Problems. Choose to view inside "a". You will see the problem, but its path is presented as "file.pg" when it should be "a/file.pg". If you add the problem to a set, the path that is added will just be "file.pg", so then when you visit the set, it doesn't find the problem file.

I have tested and this appears to happen only for single-letter folders. If you move "a" to "aa" and try again, you see the correct path.

I haven't gone hunting in the code for where the error is coming from, hoping that someone knows where to look for this.

**Comment by drgrice1** [comment] 2022-09-12 22:53
The problem is line 1221 of lib/WeBWorK/ContentGenerator/Instructor/SetMaker.pm.  On that line a regular expression is supposed to "clean up top ugliness".  The regular expression is faulty.  The line is currently `$sourceFileName =~ s|^./||;`.  I think that it was intended to remove the string "./" from the beginning of the path if it is there.  However, the dot in a regular expression doesn't mean a literal dot in a string.  It means any single character.  So what happens is it removes anything single character at the beginning of the `$sourceFileName` that is immediately followed by a forward slash.  That line should be `$sourceFileName =~ s|^\./||;`.

**Comment by pstaabp** [comment] 2022-11-16 18:00
Now fixed.

**Closed** 2022-11-16 18:00 UTC
