### ISSUE TITLE
Resume work on TikZ support

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#418] opened 2019-08-20 08:20 UTC
Draft code - see:
  - https://github.com/openwebwork/pg/pull/292
  - http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4625

Alternate approach - `tikzjax` - see:
  - http://tikzjax.com/
  - http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4616

**Comment by mgage** [comment] 2019-08-22 19:50
What I planned to do next was to imitate what is done in
https://github.com/openwebwork/webwork2/blob/master/clients/sendXMLRPC.pl#L942
which in turn is a simplified version of code found in 
webwork2/lib/WeBWorK/ContentGenerator/Hardcopy.pm 

1. create a containing directory (with a uniqID) in something like pg/DATA
2. dump files into it including the tikz code,
3. run pdflatex on it,
4. move the result to somewhere useful
5. then remove the containing directory to clean things up.

Also make sure it gets indexed properly by alias() ) At the moment alias() may not be indexing pdf files and svg files but we can fix that as well. They should be treated much like html pages -- they don't need any converting - these just need to aliases and stored.

**Comment by mgage** [comment] 2019-08-26 18:02
That’s fine Sean.  What laptop do you use?  Can you install Docker on it?  That makes a great testing environment
and doesn’t interfere with your other work.

I’m going to be a bit unresponsive myself.  Classes start Wednesday.  :-)

Take care,

Mike


On Aug 26, 2019, at 1:31 PM, sean-fitzpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you just put this directory in /tmp? Then it should be cleaned automatically by the OS.
I guess maybe the issue is if you have 100 students all running the problem and if the image needs to be generated each time, then /tmp could fill up quickly.

I'm going to have to revert our server back to 2-15 -- classes are starting next week!
We were supposed to get a testing server running this summer but budget politics and other issues got in the way.

We're supposed to be getting a new server soon. I can run that one as a testing server for awhile since it won't be here in time for start of term. In the meantime course prep is forcing me offline for awhile but I'll keep my eye on this. Thanks for looking at it again.

**Comment by drgrice1** [comment] 2019-09-29 16:33
You should note that I have what I consider a fully function implementation of Tikz in the tikz-image branch of my fork (there is both a webwork and pg portion).  I have been planning to put that in as a pull request to develop once 2.15 is release.

**Comment by mgage** [comment] 2019-09-29 18:08
Thanks for finishing this.  I've noticed it in your github branches but haven't had time to check it out.   Why don't you submit it as a pull request now.  Mark it as milestone PG-2.16 so we don't try to merge it right away. I'll close this pull request in favor of yours.  If we notice anything missing once we start working on your tikz implementation we can revive this pull request if necessary.

**Closed** 2020-05-19 17:36 UTC
