### ISSUE TITLE
Automatic correct answer for answers with units

### ISSUE THREAD

**Issue by pkohl** [openwebwork/pg#740] opened 2022-10-20 17:59 UTC
Hey folks,

Short version:  Entering an answer with units as 0 with an extra m/A appended to the units appears to always result in a green box, even if the answer isn't supposed to be zero.

Long version:  We found what appears to be a way to get a green box for any problem that requests an answer with units, if those units aren't compound units.  So, it applies if a problem asks for a number with units of V, T, or N, but not one that asks for an answer with units of m/s.

As I understand things, Webwork interprets A as Angstroms, so if one were to append m/A to an answer, it wouldn't change the dimensional correctness of the answer, but it would add several factors of 10 the number, which should result in the answer being evaluated as incorrect.  And it usually does, unless one puts in the number zero.  So if the answer to a problem is supposed to be "5 V", "0 V*m/A" gets a green box.  Unless we're doing something wrong with our code, this appears to be reproducible.  I'm including a couple screenshots of the answer reports and the code for one of the offending problems.

I've had issues with the difference between numbers and strings before, especially when small numbers are involved, and I tried massaging the answer variable with Real(), Compute(), and Compute(uc()).  It doesn't look like NumberWithUnits will take the output from Real() or Compute(uc()).  It does look like it'll take the output from Real(), but it doesn't fix the problem.  Still, I'm definitely not sure that this isn't user error.  Any suggestions would be appreciated.

<img width="705" alt="WebworkZeroBug_PHGN100" src="https://user-images.githubusercontent.com/29390081/197022780-5680ddc3-df09-424f-88be-bcd4cc95a6be.PNG">
<img width="731" alt="WebworkZeroBug_B" src="https://user-images.githubusercontent.com/29390081/197022782-8904e530-d3bb-47cb-b354-eb4a43b5f788.PNG">
<img width="677" alt="WebworkZeroBug_A" src="https://user-images.githubusercontent.com/29390081/197022784-0b990168-74c2-4619-b9b6-6d21fce40040.PNG">

Code example: 

DOCUMENT();
loadMacros(
"PGstandard.pl",
"PGgraphmacros.pl",
"parserPopUp.pl",
"PGML.pl",
"MathObjects.pl",
"parserMultiAnswer.pl",
"scaffold.pl",
"PGcourse.pl",
"PGessaymacros.pl",
"parserNumberWithUnits.pl",
"PGchoicemacros.pl",
"Constants.pg",
"parserRadioButtons.pl",
"Functions.pg"
);
$showPartialCorrectAnswers = 1;
Context("Numeric");
Context()->texStrings();
Context()->flags->set(tolerance => 0.03);

$ro=random(47.,71.,2.);
$i=random(5.,9.,.1);
$ri=random(31.,43.,2.);

$B=$MU_0*$i*(100./$ri-100./$ro)/12.;
$BUnit=NumberWithUnits("$B T");

BEGIN_TEXT
<h1 style="color:#0000EE">Concentric Arcs</h1>
The closed loop shown in the figure below carries a current of \($i ~\mathrm{A}\) in the counterclockwise direction. The radius of the outer arc is \($ro ~\mathrm{cm}\), that of the inner arc is \($ri ~\mathrm{cm}\). Find the magnitude of the magnetic field at point \(P\) if the angle \(\theta=60^\circ\).
$BR
\{ image('ConcentricArcs.gif', width=>400, height=>400) \}
END_TEXT

BEGIN_PGML
[`Bfield`]=[__________________________]{$BUnit}
END_PGML

ENDDOCUMENT();

**Comment by Alex-Jordan** [comment] 2022-10-22 20:35
I transferred it to PG. It was webwork2 #1815, now it is pg #740.

**Comment by drgrice1** [comment] 2022-10-22 23:59
A few things that I have seen so far on this.  It happens with and without MathQuill enabled.  It is not due to the new MathQuill parsing, and there isn't a regression introduced by that either as it happens with previous versions of pg as well.

Part of the issue seems to be in the regular expression parsing in the `splitUnits` function in `lib/Parser/Legacy/NumberWithUnits.pm`.  For the first answer that is entered as `0.011 Tm/A` the `splitUnits` methods returns `$num` and `$units` both undefined.  That is the reason for the message `Your answer doesn't look like a number with units`.

Another part of the issue is that the NumberWithUnits objects are not "stateful".  The first and second answer both use the `$A` object for the answer.  NumberWithUnits objects can't handle `evaluate` calls.  This is actually a known issue.  See the `todo` test at the end of `t/units/basic_parser.t`.

The final part of the issue, that is the original issue here with the answer being marked correct when it shouldn't, I haven't figured out what is causing that yet.

**Comment by drgrice1** [comment] 2022-10-23 00:05
Actually, looking further at the `Tm/A` part of this, units in general are not designed to be able to handle multiplication.  The same things happens with a Newton meter.  You have to type `N m` or `N*m` for that to work.  So I am not sure that is technically an issue according to the design of units in pg at this point.  That would be a feature request for future improvements to the way that units work.

**Comment by Alex-Jordan** [comment] 2022-10-23 01:13
Confirming some things Glenn says (and I should have brought up earlier): OP is using Runestone hosting, still using version 2.16, and not using MathQuill.

**Comment by Alex-Jordan** [comment] 2022-10-23 02:17
Note that, as Pat says, this bug opens up a way for students to get any NumberWithUnits answers accepted as correct as long as you have the basic dimension correct. Say the correct answer is `50 kg` for example. You can just enter `0 kg m^2/A^2` and it will be accepted. Or `0 kg^6/g^5`. Or `0 kg parsec/m`.

**Comment by drgrice1** [comment] 2022-10-23 10:55
Clearly this needs to be fixed!  I think that adjusting the student answer instead of the correct answer would work.  I am not sure how hard it is to make that change though.

**Comment by pstaabp** [comment] 2023-04-11 10:41
This was fixed in openwebwork/pg#740

**Closed by pstaabp** 2023-04-11 10:41 UTC
